### ISSUE TITLE
LIWCalike installation error

### ISSUE THREAD

**Issue by anonym0305** [kbenoit/LIWCalike#1] opened 2017-03-02 15:28 UTC
I tried to install LIWCalike but ran into error.  I tried to install MKL and RevoUtilsMath packages but couldn't locate/install them. 

> devtools::install_github("kbenoit/LIWCalike")
Downloading GitHub repo kbenoit/LIWCalike@master
from URL https://api.github.com/repos/kbenoit/LIWCalike/zipball/master
Installing LIWCalike
Installing 1 package: stringi
Installing package into ‘C:/Users/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/3.3/stringi_1.1.2.zip'
Content type 'application/zip' length 14264581 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘stringi’

Error : .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: NULL
  error: To use RevoUtilsMath you must first install the MKL Math Library.
Visit http://mran.revolutionanalytics.com/download.
If you have previously installed the MKL Math Library,
remove it using Add/Remove Programs, then re-install.
Error: package or namespace load failed for 'RevoUtilsMath'
Execution halted
Error: Command failed (1)

**Comment by kbenoit** [comment] 2017-03-02 16:42
Should be fixed now, and working with the newest **quanteda**.

**Closed as completed by kbenoit** 2017-03-02 16:42 UTC

**Comment by anonym0305** [comment] 2017-03-02 17:17
This is what I'm seeing...

> install.packages("quanteda")
Installing package into ‘C:/Users/svaid/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
          binary  source needs_compilation
quanteda 0.9.8.3 0.9.8.5              TRUE

  Binaries will be installed
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/3.3/quanteda_0.9.8.3.zip'
Content type 'application/zip' length 4245276 bytes (4.0 MB)
downloaded 4.0 MB

package ‘quanteda’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\s\AppData\Local\Temp\Rtmp4uviJh\downloaded_packages
> devtools::install_github("kbenoit/LIWCalike")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name

**Comment by kbenoit** [comment] 2017-03-02 17:18
See the DESCRIPTION for dependencies.  You will need to have R >= 3.2.2 and quanteda >= 0.9.9.

Suggest before you install **LIWCalike**, you first run

```r
update.packages(ask = FALSE)
```

**Comment by anonym0305** [comment] 2017-03-02 17:28
I have R version 3.3.2, but am unable to install quanteda >=0.9.9. Every time I reinstall quanteda on R Studio I'm able to only install quanteda 9.8.3, as above.

**Comment by kbenoit** [comment] 2017-03-02 17:58
sessionInfo()?

Sent from my iPhone

On 2 Mar 2017, at 17:29, anonymousBlueDevil <notifications@github.com<mailto:notifications@github.com>> wrote:


I have R version 3.3.2, but am unable to install quanteda >=0.9.9. Every time I reinstall quanteda on R Studio I'm able to only install quanteda 9.8.3, as above.

**Comment by anonym0305** [comment] 2017-03-02 18:05
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'curl' is missing or broken

**Comment by kbenoit** [comment] 2017-03-02 19:53
I have no idea why you are unable to install the newest **quanteda** version from CRAN. On my Windows 7 virtual machine, it installs just fine. Same OS and R version as yours.

```

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2
> install.packages("quanteda")
Installing package into ‘C:/Users/kbenoit/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/quanteda_0.9.9-24.zip'
Content type 'application/zip' length 5567649 bytes (5.3 MB)
downloaded 5.3 MB

package ‘quanteda’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kbenoit\AppData\Local\Temp\RtmpA5I5e1\downloaded_packages
```

**Comment by anonym0305** [comment] 2017-03-02 20:51
Here are all the steps I took...

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] RevoUtils_10.0.2 tools_3.3.2     
> update.packages(ask = FALSE)
Warning: package 'RUnit' in library 'C:/Program Files/Microsoft/MRO-3.3.2/library' will not be updated
Warning: package 'survival' in library 'C:/Program Files/Microsoft/MRO-3.3.2/library' will not be updated

  There are binary versions available but the source versions are later:
          binary  source needs_compilation
quanteda 0.9.8.3 0.9.8.5              TRUE
R.oo      1.20.0  1.21.0             FALSE
survival  2.39-5  2.40-1              TRUE

  Binaries will be installed
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/3.3/quanteda_0.9.8.3.zip'
Content type 'application/zip' length 4245276 bytes (4.0 MB)
downloaded 4.0 MB

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/3.3/survival_2.39-5.zip'
Content type 'application/zip' length 4813745 bytes (4.6 MB)
downloaded 4.6 MB

package ‘quanteda’ successfully unpacked and MD5 sums checked
package ‘survival’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\s\AppData\Local\Temp\Rtmpe2bIyl\downloaded_packages
installing the source package ‘R.oo’

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/src/contrib/R.oo_1.21.0.tar.gz'
Content type 'application/octet-stream' length 403410 bytes (393 KB)
downloaded 393 KB

Error : .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: NULL
  error: To use RevoUtilsMath you must first install the MKL Math Library.
Visit http://mran.revolutionanalytics.com/download.
If you have previously installed the MKL Math Library,
remove it using Add/Remove Programs, then re-install.
Error: package or namespace load failed for 'RevoUtilsMath'
Execution halted

The downloaded source packages are in
	‘C:\Users\s\AppData\Local\Temp\Rtmpe2bIyl\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/MICROS~4/MRO-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\s\Documents\R\win-library\3.3" C:\Users\s\AppData\Local\Temp\Rtmpe2bIyl/downloaded_packages/R.oo_1.21.0.tar.gz' had status 1 
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘R.oo’ had non-zero exit status
> install.packages("quanteda")
Installing package into ‘C:/Users/s/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
          binary  source needs_compilation
quanteda 0.9.8.3 0.9.8.5              TRUE

  Binaries will be installed
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-11-01/bin/windows/contrib/3.3/quanteda_0.9.8.3.zip'
Content type 'application/zip' length 4245276 bytes (4.0 MB)
downloaded 4.0 MB

package ‘quanteda’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\s\AppData\Local\Temp\Rtmpe2bIyl\downloaded_packages
> devtools::install_github("kbenoit/LIWCalike")
Downloading GitHub repo kbenoit/LIWCalike@master
from URL https://api.github.com/repos/kbenoit/LIWCalike/zipball/master
Installing LIWCalike
"C:/PROGRA~1/MICROS~4/MRO-33~1.2/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/s/AppData/Local/Temp/Rtmpe2bIyl/devtools1d2c1f0e6419/kbenoit-LIWCalike-446aa9f"  \
  --library="C:/Users/s/Documents/R/win-library/3.3" --install-tests 

Error : .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: NULL
  error: To use RevoUtilsMath you must first install the MKL Math Library.
Visit http://mran.revolutionanalytics.com/download.
If you have previously installed the MKL Math Library,
remove it using Add/Remove Programs, then re-install.
Error: package or namespace load failed for 'RevoUtilsMath'
Execution halted
Error: Command failed (1)

**Comment by kbenoit** [comment] 2017-03-02 21:16
Maybe the problem is that the Revolution Analytics repository has only an old version of **quanteda**?

Try 
```r
chooseCRANmirror()
```
and select a more "standard" CRAN mirror.

Also you can try installing the GitHub version, see the instructions at https://github.com/kbenoit/quanteda.

**Comment by anonym0305** [comment] 2017-03-02 21:21
quanteda .9.9.24 is installed, but the error's still there.

> library("quanteda", lib.loc="~/R/win-library/3.3")
quanteda version 0.9.9.24
Using 3 of 4 cores for parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

The following object is masked from ‘package:base’:

    sample

> devtools::install_github("kbenoit/LIWCalike")
Downloading GitHub repo kbenoit/LIWCalike@master
from URL https://api.github.com/repos/kbenoit/LIWCalike/zipball/master
Installing LIWCalike
"C:/PROGRA~1/MICROS~4/MRO-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/svaid/AppData/Local/Temp/Rtmpe2bIyl/devtools1d2c5c5a2f1f/kbenoit-LIWCalike-446aa9f"  \
  --library="C:/Users/svaid/Documents/R/win-library/3.3" --install-tests 

Error : .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: NULL
  error: To use RevoUtilsMath you must first install the MKL Math Library.
Visit http://mran.revolutionanalytics.com/download.
If you have previously installed the MKL Math Library,
remove it using Add/Remove Programs, then re-install.
Error: package or namespace load failed for 'RevoUtilsMath'
Execution halted
Error: Command failed (1)

**Comment by kbenoit** [comment] 2017-03-03 10:33
I'm not sure what you are using, but it looks like the Revolution Analytics build or at least the libraries. I'd try (re)installing the MKL Math Library from the website in the error message. 

Maybe reinstall R?

**Comment by anonym0305** [comment] 2017-03-15 18:53
I almost installed LIWCalike, but got stuck at RcppArmadillo, pls see bottom. I tried to install an earlier version RcppArmadillo but I'm still stuck. 

install.packages("RcppArmadillo", version ='0.6.700.6.0',repos='http://cran.us.r-project.org')

> devtools::install_github("kbenoit/LIWCalike")
Downloading GitHub repo kbenoit/LIWCalike@master
from URL https://api.github.com/repos/kbenoit/LIWCalike/zipball/master
Installing LIWCalike
trying URL 'https://cran.revolutionanalytics.com/src/contrib/quanteda_0.9.9-24.tar.gz'
Content type 'application/octet-stream' length 4644119 bytes (4.4 MB)
==================================================
downloaded 4.4 MB

Installing quanteda
trying URL 'https://cran.revolutionanalytics.com/src/contrib/RcppArmadillo_0.7.700.0.0.tar.gz'
Content type 'application/octet-stream' length 1075328 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

Installing RcppArmadillo
'/share/apps/R-3.3.2/lib64/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpKvMnXe/devtools76e5507a4847/RcppArmadillo'  \
  --library='/home/s/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 

* installing *source* package 'RcppArmadillo' ...
** package 'RcppArmadillo' successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... no
configure: WARNING: Only g++ version 4.6 or greater can be used with RcppArmadillo.
configure: error: Please use a different compiler.
ERROR: configuration failed for package 'RcppArmadillo'
* removing '/home/s/R/x86_64-pc-linux-gnu-library/3.3/RcppArmadillo'
Error: Command failed (1)

**Comment by kbenoit** [comment] 2017-03-15 19:01
Don't need these to install either package, only this:

```r
install.packages("quanteda")
devtools::install_github("kbenoit/LIWCalike")
```
